const data = {
    products:[
        {
            _id:'1',
            name:'bitcoin',
            category:'cryptocurrency',
            image:'/images/bitcoin.jpg',
            price:'44578.30 USD',
            brand:'BTC',
            rating:'4.5',
            numReviews:'10',
            description:'high quality product',
        },
        {
            _id:'2',
            name:'ethereum',
            category:'cryptocurrency',
            image:'/images/ethereum.jpg',
            price:'3050,70 USD',
            brand:'ETH',
            rating:'4.5',
            numReviews:'10',
            description:'high quality product',
        },
        {
            _id:'3',
            name:'binance',
            category:'cryptocurrency',
            image:'/images/binance.jpg',
            price:'419,85 USD',
            brand:'BNB',
            rating:'4.5',
            numReviews:'10',
            description:'high quality product',
        },
        {
            _id:'4',
            name:'ripple',
            category:'cryptocurrency',
            image:'/images/ripple.jpg',
            price:'1.5 USD',
            brand:'XRP',
            rating:'4.5',
            numReviews:'10',
            description:'high quality product',
        },
        {
            _id:'5',
            name:'dash',
            category:'cryptocurrency',
            image:'/images/dash.jpg',
            price:'208,15 USD',
            brand:'DASH',
            rating:'4.5',
            numReviews:'10',
            description:'high quality product',
        },
        {
            _id:'6',
            name:'litecoin',
            category:'cryptocurrency',
            image:'/images/litecoin.jpg',
            price:'170,09 USD',
            brand:'LTC',
            rating:'4.5',
            numReviews:'10',
            description:'high quality product',
        },
        {
            _id:'7',
            name:'cardano',
            category:'cryptocurrency',
            image:'/images/cardano.jpg',
            price:'2,4 USD',
            brand:'ADA',
            rating:'4.5',
            numReviews:'10',
            description:'high quality product',
        },
        {
            _id:'8',
            name:'uniswap',
            category:'cryptocurrency',
            image:'/images/uniswap.jpg',
            price:'27,03 USD',
            brand:'UNI',
            rating:'4.5',
            numReviews:'10',
            description:'high quality product',
        },
        {
            _id:'9',
            name:'paxgold',
            category:'cryptocurrency',
            image:'/images/paxgold.jpg',
            price:'1788,37 USD',
            brand:'PAXG',
            rating:'4.5',
            numReviews:'10',
            description:'high quality product',
        },
        {
            _id:'10',
            name:'terra',
            category:'cryptocurrency',
            image:'/images/terra.jpg',
            price:'30,19 USD',
            brand:'LUNA',
            rating:'4.5',
            numReviews:'10',
            description:'high quality product',
        },
        {
            _id:'11',
            name:'polkadot',
            category:'cryptocurrency',
            image:'/images/polkadot.jpg',
            price:'25,23 USD',
            brand:'DOT',
            rating:'4.5',
            numReviews:'10',
            description:'high quality product',
        },
        {
            _id:'12',
            name:'tron',
            category:'cryptocurrency',
            image:'/images/tron.jpg',
            price:'0.085 USD',
            brand:'TRX',
            rating:'4.5',
            numReviews:'10',
            description:'high quality product',
        },
        {
            _id:'13',
            name:'dogecoin',
            category:'cryptocurrency',
            image:'/images/dogecoin.jpg',
            price:'0,3012 USD',
            brand:'TRX',
            rating:'4.5',
            numReviews:'10',
            description:'high quality product',
        },
        {
            _id:'14',
            name:'monero',
            category:'cryptocurrency',
            image:'/images/monero.jpg',
            price:'256,61 USD',
            brand:'XMR',
            rating:'4.5',
            numReviews:'10',
            description:'high quality product',
        },
        {
            _id:'15',
            name:'neo',
            category:'cryptocurrency',
            image:'/images/neo.jpg',
            price:'50,97 USD',
            brand:'NEO',
            rating:'4.5',
            numReviews:'10',
            description:'high quality product',
        },
        {
            _id:'16',
            name:'zcash',
            category:'cryptocurrency',
            image:'/images/zcash.jpg',
            price:'143,44 USD',
            brand:'ZEC',
            rating:'4.5',
            numReviews:'10',
            description:'high quality product',
        },
        {
            _id:'17',
            name:'perfectmoney',
            category:'cryptocurrency',
            image:'/images/perfectmoney.jpg',
            price:'USD',
            brand:'PM',
            rating:'4.5',
            numReviews:'10',
            description:'high quality product',
        },
        {
            _id:'18',
            name:'elrond',
            category:'cryptocurrency',
            image:'/images/elrond.jpg',
            price:'141.73 USD',
            brand:'EGLD',
            rating:'4.5',
            numReviews:'10',
            description:'high quality product',
        },
        {
            _id:'19',
            name:'bittorrent',
            category:'cryptocurrency',
            image:'/images/bittorrent.jpg',
            price:'0.00417 USD',
            brand:'BTT',
            rating:'4.5',
            numReviews:'10',
            description:'high quality product',
        },
        {
            _id:'20',
            name:'solana',
            category:'cryptocurrency',
            image:'/images/solana.jpg',
            price:'71.66 USD',
            brand:'SOL',
            rating:'4.5',
            numReviews:'10',
            description:'high quality product',
        },
        {
            _id:'21',
            name:'stellar',
            category:'cryptocurrency',
            image:'/images/stellar.jpg',
            price:'0.359962 USD',
            brand:'XLM',
            rating:'4.5',
            numReviews:'10',
            description:'high quality product',
        },
    ],
};
export default data;